<?php

/*
	Do not edit this file manually. This copy of global file is overwritten
	by extensions editor.
*/

$installed_extensions = array (
	1 => array(
		'name' => 'KNB Group HRM',
		'package' => 'knb_hrm',
		'version' => '1.0',
		'path' => 'modules/knb_hrm',
		'active' => true,
		'urank' => 1,
	),
	2 => array(
		'name' => 'KNB Group Banking',
		'package' => 'knb_banking',
		'version' => '1.0',
		'path' => 'modules/knb_banking',
		'active' => true,
		'urank' => 2,
	),
	3 => array(
		'name' => 'KNB Group Distribution',
		'package' => 'knb_distribution',
		'version' => '1.0',
		'path' => 'modules/knb_distribution',
		'active' => true,
		'urank' => 3,
	),
);
