<?php

/*
	Do not edit this file manually. This copy of global file is overwritten
	by extensions editor.
*/

$installed_extensions = array (
	1 => array(
		'name' => 'KNB Group HRM',
		'package' => 'knb_hrm',
		'version' => '1.0',
		'path' => 'modules/knb_hrm',
		'active' => true,
		'urank' => 1,
	),
	2 => array(
		'name' => 'KNB Group Banking',
		'package' => 'knb_banking',
		'version' => '1.0',
		'path' => 'modules/knb_banking',
		'active' => true,
		'urank' => 2,
	),
	3 => array(
		'name' => 'KNB Group Distribution',
		'package' => 'knb_distribution',
		'version' => '1.0',
		'path' => 'modules/knb_distribution',
		'active' => true,
		'urank' => 3,
	),
	4 => array(
		'name' => 'KNB Group Purchasing',
		'package' => 'knb_purchasing',
		'version' => '1.0',
		'path' => 'modules/knb_purchasing',
		'active' => true,
		'urank' => 4,
	),
	5 => array(
		'name' => 'KNB Group Inventory Extensions',
		'package' => 'knb_inventory_ext',
		'version' => '1.0',
		'path' => 'modules/knb_inventory_ext',
		'active' => true,
		'urank' => 5,
	),
	6 => array(
		'name' => 'KNB Group Production',
		'package' => 'knb_production',
		'version' => '1.0',
		'path' => 'modules/knb_production',
		'active' => true,
		'urank' => 6,
	),
	7 => array(
		'name' => 'KNB Group Sales Extensions',
		'package' => 'knb_sales_ext',
		'version' => '1.0',
		'path' => 'modules/knb_sales_ext',
		'active' => true,
		'urank' => 7,
	),
);
