<?php

/*
	Do not edit this file manually. This copy of global file is overwritten
	by extensions editor.
*/

$installed_extensions = array (
	1 => array(
		'name' => 'KNB Group HRM',
		'package' => 'knb_hrm',
		'version' => '1.0',
		'path' => 'modules/knb_hrm',
		'active' => true,
		'urank' => 1,
	),
);
